FROM node:22-alpine AS miniapp-builder

WORKDIR /build/miniapp

COPY miniapp/package*.json ./
RUN npm install

COPY miniapp ./
RUN npm run build


FROM nginx:1.27-alpine

COPY --from=miniapp-builder /build/miniapp/dist /usr/share/nginx/html
